/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Omar
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelInvestigadores = new javax.swing.JPanel();
        btnCrearInvestigadores = new javax.swing.JButton();
        btnActualizarInvestigadores = new javax.swing.JButton();
        btnCargarInvestigadores = new javax.swing.JButton();
        btnEliminarInvestigadores = new javax.swing.JButton();
        panelTablaInvestigadores = new javax.swing.JPanel();
        panelGráficaInvestigadores = new javax.swing.JPanel();
        panelMuestras = new javax.swing.JPanel();
        panelTablaMuestras = new javax.swing.JPanel();
        btnCrearMuestras = new javax.swing.JButton();
        btnCargarMuestras = new javax.swing.JButton();
        panelAsignarExperimentos = new javax.swing.JPanel();
        labelAsignarInvestigador = new javax.swing.JLabel();
        labelAsignarMuestra = new javax.swing.JLabel();
        comboboxInvestigadores = new javax.swing.JComboBox<>();
        comboboxMuestras = new javax.swing.JComboBox<>();
        btnAsignarExperimento = new javax.swing.JButton();
        panelPatrones = new javax.swing.JPanel();
        panelTablaPatrones = new javax.swing.JPanel();
        btnCrearPatrones = new javax.swing.JButton();
        btnCargarPatrones = new javax.swing.JButton();
        btnEliminarPatrones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador - IPC Quimik");

        panelInvestigadores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCrearInvestigadores.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnCrearInvestigadores.setText("Crear");

        btnActualizarInvestigadores.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        btnActualizarInvestigadores.setText("Actualizar");

        btnCargarInvestigadores.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        btnCargarInvestigadores.setText("Cargar");

        btnEliminarInvestigadores.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        btnEliminarInvestigadores.setText("Eliminar");

        javax.swing.GroupLayout panelTablaInvestigadoresLayout = new javax.swing.GroupLayout(panelTablaInvestigadores);
        panelTablaInvestigadores.setLayout(panelTablaInvestigadoresLayout);
        panelTablaInvestigadoresLayout.setHorizontalGroup(
            panelTablaInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        panelTablaInvestigadoresLayout.setVerticalGroup(
            panelTablaInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGráficaInvestigadoresLayout = new javax.swing.GroupLayout(panelGráficaInvestigadores);
        panelGráficaInvestigadores.setLayout(panelGráficaInvestigadoresLayout);
        panelGráficaInvestigadoresLayout.setHorizontalGroup(
            panelGráficaInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGráficaInvestigadoresLayout.setVerticalGroup(
            panelGráficaInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInvestigadoresLayout = new javax.swing.GroupLayout(panelInvestigadores);
        panelInvestigadores.setLayout(panelInvestigadoresLayout);
        panelInvestigadoresLayout.setHorizontalGroup(
            panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestigadoresLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelTablaInvestigadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInvestigadoresLayout.createSequentialGroup()
                        .addGroup(panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearInvestigadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarInvestigadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCargarInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelGráficaInvestigadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelInvestigadoresLayout.setVerticalGroup(
            panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestigadoresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInvestigadoresLayout.createSequentialGroup()
                        .addGroup(panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelInvestigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelGráficaInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTablaInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Investigadores", panelInvestigadores);

        panelMuestras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelTablaMuestrasLayout = new javax.swing.GroupLayout(panelTablaMuestras);
        panelTablaMuestras.setLayout(panelTablaMuestrasLayout);
        panelTablaMuestrasLayout.setHorizontalGroup(
            panelTablaMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        panelTablaMuestrasLayout.setVerticalGroup(
            panelTablaMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        btnCrearMuestras.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnCrearMuestras.setText("Crear");

        btnCargarMuestras.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnCargarMuestras.setText("Cargar");

        javax.swing.GroupLayout panelMuestrasLayout = new javax.swing.GroupLayout(panelMuestras);
        panelMuestras.setLayout(panelMuestrasLayout);
        panelMuestrasLayout.setHorizontalGroup(
            panelMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMuestrasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelTablaMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearMuestras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarMuestras, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMuestrasLayout.setVerticalGroup(
            panelMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMuestrasLayout.createSequentialGroup()
                .addGroup(panelMuestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMuestrasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelTablaMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMuestrasLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnCrearMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Muestras", panelMuestras);

        panelAsignarExperimentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelAsignarInvestigador.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelAsignarInvestigador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAsignarInvestigador.setText("Investigador");

        labelAsignarMuestra.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelAsignarMuestra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAsignarMuestra.setText("Muestra");

        comboboxInvestigadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboboxInvestigadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboboxMuestras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboboxMuestras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAsignarExperimento.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnAsignarExperimento.setText("Asignar");

        javax.swing.GroupLayout panelAsignarExperimentosLayout = new javax.swing.GroupLayout(panelAsignarExperimentos);
        panelAsignarExperimentos.setLayout(panelAsignarExperimentosLayout);
        panelAsignarExperimentosLayout.setHorizontalGroup(
            panelAsignarExperimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignarExperimentosLayout.createSequentialGroup()
                .addGroup(panelAsignarExperimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsignarExperimentosLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panelAsignarExperimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAsignarExperimentosLayout.createSequentialGroup()
                                .addComponent(labelAsignarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboboxInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAsignarExperimentosLayout.createSequentialGroup()
                                .addComponent(labelAsignarMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboboxMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelAsignarExperimentosLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnAsignarExperimento, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelAsignarExperimentosLayout.setVerticalGroup(
            panelAsignarExperimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignarExperimentosLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelAsignarExperimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAsignarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxInvestigadores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAsignarExperimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAsignarMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxMuestras, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAsignarExperimento, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignación de Experimentos", panelAsignarExperimentos);

        panelPatrones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelTablaPatronesLayout = new javax.swing.GroupLayout(panelTablaPatrones);
        panelTablaPatrones.setLayout(panelTablaPatronesLayout);
        panelTablaPatronesLayout.setHorizontalGroup(
            panelTablaPatronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        panelTablaPatronesLayout.setVerticalGroup(
            panelTablaPatronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        btnCrearPatrones.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnCrearPatrones.setText("Crear");

        btnCargarPatrones.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnCargarPatrones.setText("Cargar");

        btnEliminarPatrones.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnEliminarPatrones.setText("Eliminar");

        javax.swing.GroupLayout panelPatronesLayout = new javax.swing.GroupLayout(panelPatrones);
        panelPatrones.setLayout(panelPatronesLayout);
        panelPatronesLayout.setHorizontalGroup(
            panelPatronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPatronesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelTablaPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPatronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelPatronesLayout.setVerticalGroup(
            panelPatronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPatronesLayout.createSequentialGroup()
                .addGroup(panelPatronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPatronesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panelTablaPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPatronesLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnCrearPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPatrones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patrones", panelPatrones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarInvestigadores;
    private javax.swing.JButton btnAsignarExperimento;
    private javax.swing.JButton btnCargarInvestigadores;
    private javax.swing.JButton btnCargarMuestras;
    private javax.swing.JButton btnCargarPatrones;
    private javax.swing.JButton btnCrearInvestigadores;
    private javax.swing.JButton btnCrearMuestras;
    private javax.swing.JButton btnCrearPatrones;
    private javax.swing.JButton btnEliminarInvestigadores;
    private javax.swing.JButton btnEliminarPatrones;
    private javax.swing.JComboBox<String> comboboxInvestigadores;
    private javax.swing.JComboBox<String> comboboxMuestras;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAsignarInvestigador;
    private javax.swing.JLabel labelAsignarMuestra;
    private javax.swing.JPanel panelAsignarExperimentos;
    private javax.swing.JPanel panelGráficaInvestigadores;
    private javax.swing.JPanel panelInvestigadores;
    private javax.swing.JPanel panelMuestras;
    private javax.swing.JPanel panelPatrones;
    private javax.swing.JPanel panelTablaInvestigadores;
    private javax.swing.JPanel panelTablaMuestras;
    private javax.swing.JPanel panelTablaPatrones;
    // End of variables declaration//GEN-END:variables
}
