
package interfaces;

import archivo.ArchivoBinarioInvestigador;
import ipc_quimik.Investigador;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar
 */
public class EditarInvestigador extends javax.swing.JFrame {
        
        Administrador ventanaAdmin;
    
    /**
     * Creates new form CrearInvestigador
     */
    public EditarInvestigador(Administrador ventanaAdmin) {
        this.ventanaAdmin = ventanaAdmin;
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelCódigo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        txtCodigoEditarInvestigador = new javax.swing.JTextField();
        txtNombreEditarInvestigador = new javax.swing.JTextField();
        txtGeneroEditarInvestigador = new javax.swing.JTextField();
        txtContraseniaEditarInvestigador = new javax.swing.JTextField();
        btnActualizarInvestigador = new javax.swing.JButton();
        btnBuscarInvestigador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Investigador");
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 23)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Editar Investigador");

        labelCódigo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelCódigo.setForeground(new java.awt.Color(255, 255, 255));
        labelCódigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCódigo.setText("Código:");

        labelNombre.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre:");

        labelGenero.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(255, 255, 255));
        labelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenero.setText("Género:");

        labelContrasena.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        labelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContrasena.setText("Contraseña:");

        btnActualizarInvestigador.setBackground(new java.awt.Color(153, 153, 153));
        btnActualizarInvestigador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnActualizarInvestigador.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarInvestigador.setText("Actualizar");
        btnActualizarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInvestigadorActionPerformed(evt);
            }
        });

        btnBuscarInvestigador.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscarInvestigador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarInvestigador.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarInvestigador.setText("Buscar");
        btnBuscarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInvestigadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContraseniaEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGeneroEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnActualizarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigoEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarInvestigador)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarInvestigador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseniaEditarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnActualizarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInvestigadorActionPerformed
        ArchivoBinarioInvestigador archivo = new ArchivoBinarioInvestigador ();
        ArrayList<Investigador> listaInvestigadores = archivo.obtenerContenido("investigadores.bin");
        
        //Recorremos el arrayList Obtenido con los investigadores para buscar la coincidencia con el código ingresado
        for (Investigador investigador : listaInvestigadores) {
            //Si el código del investigador es igual al ingresado, en cada campo va a setear sus datos
            if (investigador.getCodigo().equals(txtCodigoEditarInvestigador.getText())) {
                txtNombreEditarInvestigador.setText(investigador.getNombre());
                txtGeneroEditarInvestigador.setText(investigador.getGenero());
                txtContraseniaEditarInvestigador.setText(investigador.getContrasenia());
            }
        }
        //Si alguno de los campos está vacío luego de la búsqueda es porque el código ingresado no es válido.
        if(txtNombreEditarInvestigador.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Código no válido");
        }
    }//GEN-LAST:event_btnBuscarInvestigadorActionPerformed

    private void btnActualizarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInvestigadorActionPerformed
        //instanciar el binario y llamar al procedimiento modificarContenido
        ArchivoBinarioInvestigador archivo = new ArchivoBinarioInvestigador();
        //Validamos que no hayan campos vacíos
            if((txtNombreEditarInvestigador.getText().length() != 0) && (txtGeneroEditarInvestigador.getText().length() != 0) && (txtContraseniaEditarInvestigador.getText().length() != 0)) {
            archivo.modificarContenido("Investigadores.bin", txtCodigoEditarInvestigador.getText(), new Investigador(txtCodigoEditarInvestigador.getText(), txtNombreEditarInvestigador.getText(), txtGeneroEditarInvestigador.getText(), txtContraseniaEditarInvestigador.getText(), obtenerCantExp(archivo, txtCodigoEditarInvestigador.getText())));
            
            JOptionPane.showMessageDialog(this, "El investigador fue modificado correctamente");
            txtCodigoEditarInvestigador.setText("");
            txtNombreEditarInvestigador.setText("");
            txtGeneroEditarInvestigador.setText("");
            txtContraseniaEditarInvestigador.setText("");
            this.ventanaAdmin.actualizarTabla();
            }
            else {
                JOptionPane.showMessageDialog(this, "Falta información");
            }
    }//GEN-LAST:event_btnActualizarInvestigadorActionPerformed

    //Creamos función para retornar el número de experimentos de cada Investigador almacenado en el binario
    //Esta funcion es usada para enviarle al constructor del investigador instanciado en el método "modificarContenido" del archivo binario, el número de experimentos que ya tenía el investigador.
    private int obtenerCantExp (ArchivoBinarioInvestigador archivo, String codigo) {
        int cantidadExperimentos = 0; //Declaramos la variable que retornaremos con el número de investigadores
        //Declaramos un arraylist para guardar lo que tiene el binario, para ello previamente solicitamos por parámetro el binario.
        ArrayList<Investigador> lista_investigadores = archivo.obtenerContenido("investigadores.bin");
        //Recorremos la lista de investigadores y almacenamos la cantidad de experimentos del investigador deseado
        for (Investigador invest : lista_investigadores){
            if(invest.getCodigo().equals(codigo))
                cantidadExperimentos = invest.getExperimentos();
        }
        //retornamos la cantidad de experimentos del Investigador
        return cantidadExperimentos;
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarInvestigador;
    private javax.swing.JButton btnBuscarInvestigador;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelCódigo;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtCodigoEditarInvestigador;
    private javax.swing.JTextField txtContraseniaEditarInvestigador;
    private javax.swing.JTextField txtGeneroEditarInvestigador;
    private javax.swing.JTextField txtNombreEditarInvestigador;
    // End of variables declaration//GEN-END:variables
}
